// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Language_and_skill_feature.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("language feature")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("Language")]
    public partial class LanguageFeatureFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "Language"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "language feature", "As a registered user I want to login to the portal with valid credentials \r\nand a" +
                "dd, edit and delete records in the language and skill module\r\nso that i can show" +
                " my language and skill proficiency", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Language.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 9
#line hidden
#line 10
 await testRunner.GivenAsync("I logged into the portal succesfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 11
 await testRunner.AndAsync("I navigate to the profile page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Language.feature.ndjson", 20);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Create new language record with valid data")]
        [global::NUnit.Framework.CategoryAttribute("addlanguagerecordwithvaliddata")]
        [global::NUnit.Framework.TestCaseAttribute("English", "Fluent", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("French", "Basic", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("German", "Basic", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("Spanish", "Conversational", "3", null)]
        public async global::System.Threading.Tasks.Task CreateNewLanguageRecordWithValidData(string languageName, string proficiencyLevel, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "addlanguagerecordwithvaliddata"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("languageName", languageName);
            argumentsOfScenario.Add("proficiencyLevel", proficiencyLevel);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create new language record with valid data", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 15
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
#line 16
 await testRunner.WhenAsync(string.Format("I create a new language record with valid \'{0}\' and \'{1}\' data", languageName, proficiencyLevel), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 17
 await testRunner.ThenAsync(string.Format("the new language record with valid \'{0}\' and \'{1}\' should be created successfully" +
                            "", languageName, proficiencyLevel), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Create new language record with blank for language name")]
        [global::NUnit.Framework.TestCaseAttribute("", "Fluent", "4", null)]
        public async global::System.Threading.Tasks.Task CreateNewLanguageRecordWithBlankForLanguageName(string languageName, string proficiencyLevel, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("languageName", languageName);
            argumentsOfScenario.Add("proficiencyLevel", proficiencyLevel);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create new language record with blank for language name", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
#line 28
 await testRunner.WhenAsync(string.Format("I create a new language record with blank \'{0}\' and valid \'{1}\' data", languageName, proficiencyLevel), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
 await testRunner.ThenAsync("I should see an error message for blank language name", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Create new language record with blank for proficiency level")]
        [global::NUnit.Framework.TestCaseAttribute("Italian", "", "5", null)]
        public async global::System.Threading.Tasks.Task CreateNewLanguageRecordWithBlankForProficiencyLevel(string languageName, string proficiencyLevel, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("languageName", languageName);
            argumentsOfScenario.Add("proficiencyLevel", proficiencyLevel);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create new language record with blank for proficiency level", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 35
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
#line 36
 await testRunner.WhenAsync(string.Format("I create a new language record with valid \'{0}\' and blank \'{1}\' data", languageName, proficiencyLevel), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
 await testRunner.ThenAsync("I should see an error message for blank proficiency level", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Create new language record with invalid data")]
        [global::NUnit.Framework.CategoryAttribute("newlanguagerecordwithinvaliddata")]
        [global::NUnit.Framework.TestCaseAttribute("ABC@123", "Fluent", "6", null)]
        public async global::System.Threading.Tasks.Task CreateNewLanguageRecordWithInvalidData(string languageName, string proficiencyLevel, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "newlanguagerecordwithinvaliddata"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("languageName", languageName);
            argumentsOfScenario.Add("proficiencyLevel", proficiencyLevel);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create new language record with invalid data", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 43
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
#line 44
 await testRunner.WhenAsync(string.Format("I create a new language record with invalid \'{0}\' and valid \'{1}\' data", languageName, proficiencyLevel), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
 await testRunner.ThenAsync(string.Format("the new language record with invalid \'{0}\' should not be created", languageName), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Check if user is unable to create a duplicate language record")]
        [global::NUnit.Framework.CategoryAttribute("newlanguagerecordwithduplicatedata")]
        public async global::System.Threading.Tasks.Task CheckIfUserIsUnableToCreateADuplicateLanguageRecord()
        {
            string[] tagsOfScenario = new string[] {
                    "newlanguagerecordwithduplicatedata"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Check if user is unable to create a duplicate language record", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 51
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "languageName",
                            "proficiencyLevel"});
                table1.AddRow(new string[] {
                            "English",
                            "Fluent"});
#line 52
 await testRunner.WhenAsync("I create a new record with valid data", ((string)(null)), table1, "When ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "languageName",
                            "proficiencyLevel"});
                table2.AddRow(new string[] {
                            "English",
                            "Fluent"});
#line 57
 await testRunner.AndAsync("I try to create another record with the same data", ((string)(null)), table2, "And ");
#line hidden
#line 62
 await testRunner.ThenAsync("I should see an error message for duplicate record", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Check if user is unable to create more than 4 language records")]
        public async global::System.Threading.Tasks.Task CheckIfUserIsUnableToCreateMoreThan4LanguageRecords()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Check if user is unable to create more than 4 language records", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 66
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "languageName",
                            "proficiencyLevel"});
                table3.AddRow(new string[] {
                            "English",
                            "Fluent"});
                table3.AddRow(new string[] {
                            "French",
                            "Basic"});
                table3.AddRow(new string[] {
                            "German",
                            "Basic"});
                table3.AddRow(new string[] {
                            "Spanish",
                            "Conversational"});
                table3.AddRow(new string[] {
                            "Russian",
                            "Fluent"});
#line 67
 await testRunner.WhenAsync("I try to create more than four records", ((string)(null)), table3, "When ");
#line hidden
#line 75
 await testRunner.ThenAsync("I should not be allowed to create more than four records", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Check if user is able to edit and save existing language record")]
        [global::NUnit.Framework.CategoryAttribute("editlanguagerecordwithvaliddata")]
        public async global::System.Threading.Tasks.Task CheckIfUserIsAbleToEditAndSaveExistingLanguageRecord()
        {
            string[] tagsOfScenario = new string[] {
                    "editlanguagerecordwithvaliddata"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Check if user is able to edit and save existing language record", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 78
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "languageName",
                            "proficiencyLevel"});
                table4.AddRow(new string[] {
                            "English",
                            "Fluent"});
#line 80
await testRunner.WhenAsync("I add new record to the language module", ((string)(null)), table4, "When ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "languageName",
                            "proficiencyLevel"});
                table5.AddRow(new string[] {
                            "Italian",
                            "Conversational"});
#line 85
 await testRunner.AndAsync("I edit the record with new data", ((string)(null)), table5, "And ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "languageName",
                            "proficiencyLevel"});
                table6.AddRow(new string[] {
                            "Italian",
                            "Conversational"});
#line 90
 await testRunner.ThenAsync("the language record should be updated with new data", ((string)(null)), table6, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Check if user is not allowed to edit and save existing record with blank language" +
            " name")]
        [global::NUnit.Framework.CategoryAttribute("editlanguagerecordwithblanklanguage")]
        [global::NUnit.Framework.TestCaseAttribute("", "Conversational", "10", null)]
        public async global::System.Threading.Tasks.Task CheckIfUserIsNotAllowedToEditAndSaveExistingRecordWithBlankLanguageName(string languageName, string proficiencyLevel, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "editlanguagerecordwithblanklanguage"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("languageName", languageName);
            argumentsOfScenario.Add("proficiencyLevel", proficiencyLevel);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Check if user is not allowed to edit and save existing record with blank language" +
                    " name", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 97
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "languageName",
                            "proficiencyLevel"});
                table7.AddRow(new string[] {
                            "Spanish",
                            "Conversational"});
#line 98
await testRunner.WhenAsync("I create a new language record", ((string)(null)), table7, "When ");
#line hidden
#line 102
await testRunner.AndAsync(string.Format("I edit the record with blank \'{0}\' and valid \'{1}\'", languageName, proficiencyLevel), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 103
await testRunner.ThenAsync("I should see an error message for blank language field", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Check if user is not allowed to edit and save existing record with blank proficie" +
            "ncy level")]
        [global::NUnit.Framework.CategoryAttribute("editlanguagerecordwithblankproficiency")]
        [global::NUnit.Framework.TestCaseAttribute("German", "", "11", null)]
        public async global::System.Threading.Tasks.Task CheckIfUserIsNotAllowedToEditAndSaveExistingRecordWithBlankProficiencyLevel(string languageName, string proficiencyLevel, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "editlanguagerecordwithblankproficiency"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("languageName", languageName);
            argumentsOfScenario.Add("proficiencyLevel", proficiencyLevel);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Check if user is not allowed to edit and save existing record with blank proficie" +
                    "ncy level", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 112
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "languageName",
                            "proficiencyLevel"});
                table8.AddRow(new string[] {
                            "Spanish",
                            "Conversational"});
#line 114
await testRunner.WhenAsync("I create a new language record", ((string)(null)), table8, "When ");
#line hidden
#line 118
 await testRunner.AndAsync(string.Format("I edit the record with valid \'{0}\' and blank \'{1}\' data", languageName, proficiencyLevel), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 119
 await testRunner.ThenAsync("I should see an error message for blank proficiency level field", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Check if user is not allowed to edit and save invalid record")]
        [global::NUnit.Framework.CategoryAttribute("editlanguagerecordwithinvaliddata")]
        [global::NUnit.Framework.TestCaseAttribute("XYZ@456", "Basic", "12", null)]
        public async global::System.Threading.Tasks.Task CheckIfUserIsNotAllowedToEditAndSaveInvalidRecord(string languageName, string proficiencyLevel, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "editlanguagerecordwithinvaliddata"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("languageName", languageName);
            argumentsOfScenario.Add("proficiencyLevel", proficiencyLevel);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Check if user is not allowed to edit and save invalid record", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 126
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "languageName",
                            "proficiencyLevel"});
                table9.AddRow(new string[] {
                            "Russian",
                            "Conversational"});
#line 128
await testRunner.WhenAsync("I create a new language record", ((string)(null)), table9, "When ");
#line hidden
#line 132
 await testRunner.AndAsync(string.Format("I edit the record with invalid \'{0}\' and \'{1}\' data", languageName, proficiencyLevel), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 133
 await testRunner.ThenAsync("I should see an error message for invalid data", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Check if user is allowed to cancel the changes made to a record")]
        [global::NUnit.Framework.CategoryAttribute("cancelchanges")]
        [global::NUnit.Framework.TestCaseAttribute("Telugu", "Conversational", "13", null)]
        public async global::System.Threading.Tasks.Task CheckIfUserIsAllowedToCancelTheChangesMadeToARecord(string languageName, string proficiencyLevel, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "cancelchanges"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("languageName", languageName);
            argumentsOfScenario.Add("proficiencyLevel", proficiencyLevel);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Check if user is allowed to cancel the changes made to a record", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 140
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "languageName",
                            "proficiencyLevel"});
                table10.AddRow(new string[] {
                            "Russian",
                            "Conversational"});
#line 142
await testRunner.WhenAsync("I create a new language record", ((string)(null)), table10, "When ");
#line hidden
#line 146
 await testRunner.AndAsync(string.Format("I edit the record with new \'{0}\' and \'{1}\' data and click cancel", languageName, proficiencyLevel), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 147
 await testRunner.ThenAsync("the language record should not be updated with new data", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Check if user is able to delete an existing language record")]
        [global::NUnit.Framework.CategoryAttribute("deletelanguagerecord")]
        public async global::System.Threading.Tasks.Task CheckIfUserIsAbleToDeleteAnExistingLanguageRecord()
        {
            string[] tagsOfScenario = new string[] {
                    "deletelanguagerecord"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Check if user is able to delete an existing language record", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 154
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "languageName",
                            "proficiencyLevel"});
                table11.AddRow(new string[] {
                            "Russian",
                            "Conversational"});
#line 156
await testRunner.WhenAsync("I create a new language record", ((string)(null)), table11, "When ");
#line hidden
#line 160
 await testRunner.AndAsync("I delete the record", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 161
 await testRunner.ThenAsync("the language record should be deleted successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Check if user is  allowed to add and save the profile description")]
        [global::NUnit.Framework.CategoryAttribute("addprofiledescription")]
        [global::NUnit.Framework.TestCaseAttribute("I am a software engineer with 5 years of experience in web development.", "15", null)]
        public async global::System.Threading.Tasks.Task CheckIfUserIsAllowedToAddAndSaveTheProfileDescription(string profileDescription, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "addprofiledescription"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("profileDescription", profileDescription);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Check if user is  allowed to add and save the profile description", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 164
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
#line 165
 await testRunner.WhenAsync(string.Format("I add a profile description with valid \'{0}\'", profileDescription), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 166
 await testRunner.ThenAsync("the profile description should be saved successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Check if user is not allowed to leave the profile description blank")]
        [global::NUnit.Framework.CategoryAttribute("blankprofiledescription")]
        public async global::System.Threading.Tasks.Task CheckIfUserIsNotAllowedToLeaveTheProfileDescriptionBlank()
        {
            string[] tagsOfScenario = new string[] {
                    "blankprofiledescription"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Check if user is not allowed to leave the profile description blank", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 173
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
#line 174
 await testRunner.WhenAsync("I delete the existing text and leave a blank for the profile description and save" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 175
 await testRunner.ThenAsync("it should show an error message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Check if user is not allowed to add more than 600 characters in profile descripti" +
            "on")]
        [global::NUnit.Framework.CategoryAttribute("profiledescriptionlessthan600characters")]
        [global::NUnit.Framework.TestCaseAttribute(@"I am a software developer with 10 years of professional experience.I am a software developer with 10 years of professional experience.I am a software developer with 10 years of professional experience.I am a software developer with 10 years of professional experience.I am a software developer with 10 years of professional experience.I am a software developer with 10 years of professional experience.I am a software developer with 10 years of professional experience.I am a software developer with 10 years of professional experience.I am a software developer with 10 years of professional experience.", "17", null)]
        public async global::System.Threading.Tasks.Task CheckIfUserIsNotAllowedToAddMoreThan600CharactersInProfileDescription(string profileDescription, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "profiledescriptionlessthan600characters"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("profileDescription", profileDescription);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Check if user is not allowed to add more than 600 characters in profile descripti" +
                    "on", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 178
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
#line 179
 await testRunner.WhenAsync(string.Format("I add a \'{0}\' with more than \"600\" characters", profileDescription), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 180
 await testRunner.ThenAsync("it should not accept additional characters", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
